"""initial schema with stores and inventory

Revision ID: 294e8463f3b1
Revises: 
Create Date: 2026-01-09 02:23:49.125808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '294e8463f3b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_inventories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('region', sa.Enum('NORTH', 'SOUTH', 'EAST', 'WEST', 'CENTRAL', 'NORTH_EAST', 'NORTH_WEST', 'SOUTH_EAST', 'SOUTH_WEST', 'NORTH_CENTRAL', 'SOUTH_CENTRAL', name='region'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('category', sa.Enum('GROCERY', 'HOUSEHOLD', 'ELECTRONICS', 'STATIONERY', 'PERSONAL_CARE', 'APPAREL', 'HOME_IMPROVEMENT', 'PET', name='category'), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('store_inventory_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['store_inventory_id'], ['store_inventories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_managers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_index(op.f('ix_store_managers_email'), 'store_managers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_managers_email'), table_name='store_managers')
    op.drop_table('store_managers')
    op.drop_table('items')
    op.drop_table('stores')
    op.drop_table('store_inventories')
    # ### end Alembic commands ###
