"""add store table and restructure relationships

Revision ID: 3b633f1dfb0e
Revises: 5705d84dd809
Create Date: 2026-01-09 02:18:45.132249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b633f1dfb0e'
down_revision: Union[str, Sequence[str], None] = '5705d84dd809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouses')
    op.add_column('items', sa.Column('store_id', sa.Uuid(), nullable=False))
    op.add_column('items', sa.Column('store_inventory_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('items_store_manager_id_fkey'), 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'stores', ['store_id'], ['id'])
    op.create_foreign_key(None, 'items', 'store_inventories', ['store_inventory_id'], ['id'])
    op.drop_column('items', 'store_manager_id')
    op.add_column('store_managers', sa.Column('store_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('uq_store_managers_email'), 'store_managers', type_='unique')
    op.create_index(op.f('ix_store_managers_email'), 'store_managers', ['email'], unique=True)
    op.create_unique_constraint(None, 'store_managers', ['store_id'])
    op.create_foreign_key(None, 'store_managers', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_managers', type_='foreignkey')
    op.drop_constraint(None, 'store_managers', type_='unique')
    op.drop_index(op.f('ix_store_managers_email'), table_name='store_managers')
    op.create_unique_constraint(op.f('uq_store_managers_email'), 'store_managers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('store_managers', 'store_id')
    op.add_column('items', sa.Column('store_manager_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(op.f('items_store_manager_id_fkey'), 'items', 'store_managers', ['store_manager_id'], ['id'])
    op.drop_column('items', 'store_inventory_id')
    op.drop_column('items', 'store_id')
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('region', postgresql.ENUM('NORTH', 'SOUTH', 'EAST', 'WEST', 'CENTRAL', name='region'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('warehouses_pkey'))
    )
    # ### end Alembic commands ###
