"""add unique constraint to store manager email

Revision ID: 5705d84dd809
Revises: 4228edf425f4
Create Date: 2026-01-09 01:48:18.295122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5705d84dd809'
down_revision: Union[str, Sequence[str], None] = '4228edf425f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create unique constraint (PostgreSQL automatically creates backing unique index)
    op.create_unique_constraint('uq_store_managers_email', 'store_managers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop constraint (PostgreSQL automatically drops the backing index)
    op.drop_constraint('uq_store_managers_email', 'store_managers', type_='unique')
    # ### end Alembic commands ###
